// ISAAC RNG correctness tests — assert pyr3's TS port produces byte-for-byte
// identical state to flam3's reference C impl.
//
// The golden fixture is generated by `tests/flam3-harness/isaac-dump.sh`,
// which compiles `tests/flam3-harness/isaac-dump.c` against
// `/tmp/flam3-ref/isaac.{c,h}` and emits the post-irandinit and
// post-one-round state for each of three seeds (zero, ascending, mixed).
//
// To regenerate: `bash tests/flam3-harness/isaac-dump.sh`.

import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  RANDSIZ,
  irandinit,
  isaacRound,
  isaacIrand,
  newIsaacState,
  packIsaacStates,
  ISAAC_STATE_U32,
  type IsaacState,
} from './isaac';

interface GoldenSnapshot {
  randcnt: number;
  randa: number;
  randb: number;
  randc: number;
  randmem: number[];
  randrsl: number[];
}

interface GoldenSeed {
  description: string;
  seed: GoldenSnapshot;
  after_irandinit: GoldenSnapshot;
  after_one_round: GoldenSnapshot;
}

interface GoldenFile {
  _format: string;
  zero_seed: GoldenSeed;
  ascending_seed: GoldenSeed;
  mixed_seed: GoldenSeed;
}

const golden = JSON.parse(
  readFileSync(join(__dirname, '..', 'tests', 'fixtures', 'isaac', 'golden.json'), 'utf8'),
) as GoldenFile;

function snapshot(s: IsaacState): GoldenSnapshot {
  return {
    randcnt: s.randcnt,
    randa: s.randa,
    randb: s.randb,
    randc: s.randc,
    randmem: Array.from(s.randmem),
    randrsl: Array.from(s.randrsl),
  };
}

function loadSeed(seed: GoldenSnapshot): IsaacState {
  const s = newIsaacState();
  s.randcnt = seed.randcnt;
  s.randa = seed.randa;
  s.randb = seed.randb;
  s.randc = seed.randc;
  for (let i = 0; i < RANDSIZ; i++) {
    s.randmem[i] = seed.randmem[i]!;
    s.randrsl[i] = seed.randrsl[i]!;
  }
  return s;
}

function expectStateEquals(actual: IsaacState, expected: GoldenSnapshot): void {
  expect(snapshot(actual)).toEqual(expected);
}

const SEEDS = ['zero_seed', 'ascending_seed', 'mixed_seed'] as const;

describe('ISAAC RNG vs flam3 golden output', () => {
  for (const seedName of SEEDS) {
    const g = golden[seedName];

    describe(seedName, () => {
      it('irandinit(state, true) matches flam3 reference state byte-for-byte', () => {
        const s = loadSeed(g.seed);
        irandinit(s, true);
        expectStateEquals(s, g.after_irandinit);
      });

      it('isaacRound() after irandinit matches flam3 reference state byte-for-byte', () => {
        const s = loadSeed(g.seed);
        irandinit(s, true);
        isaacRound(s);
        expectStateEquals(s, g.after_one_round);
      });

      it('isaacRound() preserves randmem length and randrsl length', () => {
        const s = loadSeed(g.seed);
        irandinit(s, true);
        isaacRound(s);
        expect(s.randmem.length).toBe(RANDSIZ);
        expect(s.randrsl.length).toBe(RANDSIZ);
      });
    });
  }
});

describe('isaacIrand', () => {
  it('returns randrsl values in reverse-index order (matching flam3 macro)', () => {
    // The irand macro in isaac.h:49-52 uses pre-decrement: --r->randcnt
    // (with implicit pre-decrement via !r->randcnt-- which decrements after
    // the test). After irandinit, randcnt = RANDSIZ. First irand returns
    // randrsl[RANDSIZ-1] (i.e. the LAST element), then RANDSIZ-2, etc.
    const s = loadSeed(golden.zero_seed.seed);
    irandinit(s, true);
    const expectedRandrsl = golden.zero_seed.after_irandinit.randrsl;

    // irand pre-decrements then reads, so:
    //   1st call: randcnt becomes RANDSIZ-1, returns randrsl[RANDSIZ-1]
    //   2nd call: randcnt becomes RANDSIZ-2, returns randrsl[RANDSIZ-2]
    //   ...
    //   RANDSIZ-th call: randcnt becomes 0, returns randrsl[0]
    //   (RANDSIZ+1)-th call: triggers a new isaac round + returns randrsl[RANDSIZ-1]
    for (let k = 0; k < RANDSIZ; k++) {
      const actual = isaacIrand(s);
      const expected = expectedRandrsl[RANDSIZ - 1 - k]!;
      expect(actual).toBe(expected);
    }
  });

  it('triggers isaacRound when randcnt drains, returning fresh values', () => {
    const s = loadSeed(golden.zero_seed.seed);
    irandinit(s, true);
    // Drain all RANDSIZ values from the first batch.
    for (let i = 0; i < RANDSIZ; i++) isaacIrand(s);
    // The next call should trigger a new isaac round; the returned value
    // is the last element of the post-second-round randrsl.
    const next = isaacIrand(s);
    const expected = golden.zero_seed.after_one_round.randrsl[RANDSIZ - 1]!;
    expect(next).toBe(expected);
  });
});

describe('packIsaacStates', () => {
  const SEED = 42;
  const COUNT = 4;

  it('produces a buffer of the correct byte length', () => {
    const ab = packIsaacStates(COUNT, SEED);
    expect(ab.byteLength).toBe(COUNT * ISAAC_STATE_U32 * 4);
  });

  it('is deterministic for the same (count, seed)', () => {
    const a = new Uint32Array(packIsaacStates(COUNT, SEED));
    const b = new Uint32Array(packIsaacStates(COUNT, SEED));
    expect(Array.from(a)).toEqual(Array.from(b));
  });

  it('produces distinct streams per walker', () => {
    const ab = packIsaacStates(COUNT, SEED);
    const buf = new Uint32Array(ab);
    // Compare walker 0's randmem (offset 4..19) vs walker 1's randmem.
    const w0Mem = Array.from(buf.slice(4, 4 + RANDSIZ));
    const w1Mem = Array.from(buf.slice(ISAAC_STATE_U32 + 4, ISAAC_STATE_U32 + 4 + RANDSIZ));
    expect(w0Mem).not.toEqual(w1Mem);
  });

  it('produces different output for different globalSeed', () => {
    const a = new Uint32Array(packIsaacStates(COUNT, 42));
    const b = new Uint32Array(packIsaacStates(COUNT, 43));
    expect(Array.from(a)).not.toEqual(Array.from(b));
  });

  it('writes randcnt = RANDSIZ for each walker (post-irandinit invariant)', () => {
    const ab = packIsaacStates(COUNT, SEED);
    const buf = new Uint32Array(ab);
    for (let w = 0; w < COUNT; w++) {
      const off = w * ISAAC_STATE_U32;
      // Slot 0 of each per-walker state is randcnt.
      expect(buf[off + 0]).toBe(RANDSIZ);
    }
  });
});
